version: 2

models:
  - name: fact_reviews
    description: "Fact table containing bank branch reviews with customer sentiment and topics"
    columns:
      - name: review_id
        description: "Unique identifier for each review"
        tests:
          - unique
          - not_null

      - name: branch_id
        description: "Foreign key to bank branch"
        tests:
          - not_null

      - name: branch_name
        description: "Name of the bank branch"
        tests:
          - not_null

      - name: primary_type
        description: "Type of bank branch"

      - name: region
        description: "Region where branch is located"
        tests:
          - not_null

      - name: branch_rating
        description: "Overall rating of the branch"
        tests:
          - not_null

      - name: user_rating_count
        description: "Total number of ratings for the branch"

      - name: person_id
        description: "Reviewer identifier"
        tests:
          - not_null

      - name: review_time
        description: "Timestamp of the review"
        tests:
          - not_null

      - name: review_text
        description: "The actual review content"

      - name: review_rating
        description: "Individual review rating"
        tests:
          - accepted_values:
              values: [1, 2, 3, 4, 5]

      - name: topic
        description: "Main topic of the review"
        tests:
          - accepted_values:
              values: 
                - "billing"
                - "customer service"
                - "security"
                - "ATM issues"
                - "wait times"
                - "staff behavior"
                - "mobile banking"
                - "account management"
                - "loans"
                - "other"

      - name: sentiment
        description: "Sentiment analysis result"
        tests:
          - accepted_values:
              values: ["positive", "negative", "neutral"]

      - name: review_year
        description: "Year of the review"
        tests:
          - not_null

      - name: review_month
        description: "Month of the review (1-12)"
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

      - name: review_day_of_week
        description: "Day of week (0-6, Sunday=0)"
        tests:
          - not_null
          - accepted_values:
              values: [0, 1, 2, 3, 4, 5, 6]

      - name: satisfaction_level
        description: "Categorized satisfaction level"
        tests:
          - accepted_values:
              values: ["High", "Medium", "Low"]

      - name: review_sequence_per_user
        description: "Sequential number of reviews per user"
        tests:
          - not_null

  - name: dim_bank
    description: "Bank dimension table with satisfaction metrics"
    columns:
      - name: bank_name
        description: "Name of the bank"
        tests:
          - unique
          - not_null
      - name: branch_count
        description: "Number of branches"
      - name: average_rating
        description: "Average rating across all branches"
      - name: overall_satisfaction_pct
        description: "Overall satisfaction percentage"
      - name: security_level
        description: "Security satisfaction category"
      - name: service_quality
        description: "Service quality category"
      - name: digital_maturity
        description: "Digital banking maturity level"
      - name: wait_time_category
        description: "Wait time experience category"
      - name: regional_performance
        description: "JSON object containing satisfaction metrics per region"
      - name: best_performing_region
        description: "Region with highest satisfaction score"
      - name: worst_performing_region
        description: "Region with lowest satisfaction score"
        
  - name: dim_location
    description: "Location dimension table with regional performance metrics"
    columns:
      - name: region_id
        description: "Unique identifier for each region"
        tests:
          - unique
          - not_null
      - name: BANK_OF_AFRICA_score
        description: "Satisfaction score (x/y format) for Bank of Africa in this region"
      - name: BARID_score
        description: "Satisfaction score (x/y format) for Al Barid Bank in this region"
      - name: ATTIJARI_score
        description: "Satisfaction score (x/y format) for Attijariwafa Bank in this region"
      - name: SOCIETE_GENERAL_score
        description: "Satisfaction score (x/y format) for Societe Generale in this region"
      - name: ARAB_BANK_score
        description: "Satisfaction score (x/y format) for Arab Bank in this region"
      - name: UMNIA_score
        description: "Satisfaction score (x/y format) for Umnia Bank in this region"
      - name: BMCI_score
        description: "Satisfaction score (x/y format) for BMCI in this region"
      - name: CREDIT_AGRICOLE_score
        description: "Satisfaction score (x/y format) for Credit Agricole in this region"
      - name: CFG_score
        description: "Satisfaction score (x/y format) for CFG Bank in this region"
      - name: CIH_score
        description: "Satisfaction score (x/y format) for CIH Bank in this region"
      - name: AL_AKHDAR_score
        description: "Satisfaction score (x/y format) for Al Akhdar Bank in this region"
      - name: CREDIT_dU_MAROC_score
        description: "Satisfaction score (x/y format) for Credit du Maroc in this region"
      - name: AL_YOUSR_score
        description: "Satisfaction score (x/y format) for Bank Al Yousr in this region"
      - name: BANQUE_POPULAIRE_score
        description: "Satisfaction score (x/y format) for Banque Populaire in this region"
      - name: topic_performance
        description: "JSON object containing satisfaction scores (x/y format) per topic"
      - name: best_topic
        description: "Topic with highest satisfaction score in this region"
      - name: worst_topic
        description: "Topic with lowest satisfaction score in this region"
  - name: dim_topic
    description: "Topic dimension table with bank and regional performance metrics"
    columns:
      - name: topic_id
        description: "Topic identifier (e.g., billing, security, etc.)"
        tests:
          - unique
          - not_null
          - accepted_values:
              values: ["billing", "customer service", "security", "ATM issues", 
                      "wait times", "staff behavior", "mobile banking", 
                      "account management", "loans", "other"]
      - name: BOA_score
        description: "Satisfaction score (x/y format) for Bank of Africa for this topic"
      - name: ABB_score
        description: "Satisfaction score (x/y format) for Al Barid Bank for this topic"
      - name: ATTIJARI_score
        description: "Satisfaction score (x/y format) for Attijariwafa Bank for this topic"
      - name: SG_score
        description: "Satisfaction score (x/y format) for Societe Generale for this topic"
      - name: AB_score
        description: "Satisfaction score (x/y format) for Arab Bank for this topic"
      - name: UMNIA_score
        description: "Satisfaction score (x/y format) for Umnia Bank for this topic"
      - name: BMCI_score
        description: "Satisfaction score (x/y format) for BMCI for this topic"
      - name: CA_score
        description: "Satisfaction score (x/y format) for Credit Agricole for this topic"
      - name: CFG_score
        description: "Satisfaction score (x/y format) for CFG Bank for this topic"
      - name: CIH_score
        description: "Satisfaction score (x/y format) for CIH Bank for this topic"
      - name: AAB_score
        description: "Satisfaction score (x/y format) for Al Akhdar Bank for this topic"
      - name: CDM_score
        description: "Satisfaction score (x/y format) for Credit du Maroc for this topic"
      - name: BAY_score
        description: "Satisfaction score (x/y format) for Bank Al Yousr for this topic"
      - name: BP_score
        description: "Satisfaction score (x/y format) for Banque Populaire for this topic"
      - name: region_performance
        description: "JSON object containing satisfaction scores (x/y format) per region"
      - name: best_region
        description: "Region with highest satisfaction score for this topic"
      - name: worst_region
        description: "Region with lowest satisfaction score for this topic"
  - name: dim_week
    description: "Day of week dimension table with time-based satisfaction metrics"
    columns:
      - name: day_id
        description: "Day of week identifier (0-6, Sunday=0)"
        tests:
          - unique
          - not_null
          - accepted_values:
              values: [0, 1, 2, 3, 4, 5, 6]
      - name: day_name
        description: "Name of the day"
        tests:
          - not_null
      - name: overall_satisfaction
        description: "Overall satisfaction score (x/y format) for this day"
      - name: early_morning_satisfaction
        description: "Satisfaction score (x/y format) for 5:00 AM - 8:00 AM"
      - name: morning_satisfaction
        description: "Satisfaction score (x/y format) for 8:00 AM - 12:00 PM"
      - name: afternoon_satisfaction
        description: "Satisfaction score (x/y format) for 12:00 PM - 5:00 PM"
      - name: evening_satisfaction
        description: "Satisfaction score (x/y format) for 5:00 PM - 9:00 PM"
      - name: night_satisfaction
        description: "Satisfaction score (x/y format) for 9:00 PM - 12:00 AM"
      - name: late_night_satisfaction
        description: "Satisfaction score (x/y format) for 12:00 AM - 5:00 AM"
  - name: dim_year
    description: "Month dimension table with intra-month satisfaction metrics"
    columns:
      - name: month_id
        description: "Month number (1-12)"
        tests:
          - unique
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
      - name: month_name
        description: "Name of the month"
        tests:
          - not_null
      - name: overall_satisfaction
        description: "Overall satisfaction score (x/y format) for this month"
      - name: early_month_satisfaction
        description: "Satisfaction score (x/y format) for days 1-10"
      - name: mid_month_satisfaction
        description: "Satisfaction score (x/y format) for days 11-20"
      - name: late_month_satisfaction
        description: "Satisfaction score (x/y format) for days 21-31"
sources:
  - name: unique_source
    database: bank_reviews
    schema: public
    tables:
      - name: fact_branches