version: '3.8'
services:
  postgres_db1:
    image: postgres:latest
    container_name: postgres_db1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_1}
    ports:
      - "${POSTGRES_PORT1}:5432"
    volumes:
      - postgres_db1_data:/var/lib/postgresql/data
    restart: always

  postgres_db2:
    image: postgres:latest
    container_name: postgres_db2
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_2}
    ports:
      - "${POSTGRES_PORT2}:5432"
    volumes:
      - postgres_db2_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_db1_data:
  postgres_db2_data:
